//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FischerDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class companytablereference
    {
        public decimal CompanyTableReferenceRecordId { get; set; }
        public decimal CompanyRecordId { get; set; }
        public string TableName { get; set; }
        public decimal TableCompanyRecordId { get; set; }
    
        public virtual company company { get; set; }
    }
}
