//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FischerDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.activities = new HashSet<activity>();
            this.groups = new HashSet<group>();
            this.jobcostlevels = new HashSet<jobcostlevel>();
            this.potypes = new HashSet<potype>();
            this.stages = new HashSet<stage>();
            this.companytablereferences = new HashSet<companytablereference>();
        }
    
        public decimal CompanyRecordId { get; set; }
        public string CompanyId { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual ICollection<activity> activities { get; set; }
        public virtual ICollection<group> groups { get; set; }
        public virtual ICollection<jobcostlevel> jobcostlevels { get; set; }
        public virtual ICollection<potype> potypes { get; set; }
        public virtual ICollection<stage> stages { get; set; }
        public virtual ICollection<companytablereference> companytablereferences { get; set; }
    }
}
