//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FischerDataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class fischerhomesEntities : DbContext
    {
        public fischerhomesEntities()
            : base("name=fischerhomesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity> activities { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<companytablereference> companytablereferences { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<jobcostlevel> jobcostlevels { get; set; }
        public virtual DbSet<potype> potypes { get; set; }
        public virtual DbSet<stage> stages { get; set; }
    }
}
