//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FischerDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class potype
    {
        public potype()
        {
            this.activities = new HashSet<activity>();
        }
    
        public decimal POTypeRecordId { get; set; }
        public decimal CompanyRecordId { get; set; }
        public string POTypeId { get; set; }
        public Nullable<decimal> AccountRecordId { get; set; }
        public Nullable<bool> AllowAdjustment { get; set; }
        public string Description { get; set; }
        public Nullable<bool> EstimateHold { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public decimal JobCostLevelRecordId { get; set; }
        public Nullable<bool> POOnly { get; set; }
        public Nullable<bool> ReleasePO { get; set; }
        public Nullable<bool> VPOOnly { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual ICollection<activity> activities { get; set; }
        public virtual company company { get; set; }
        public virtual jobcostlevel jobcostlevel { get; set; }
    }
}
